[package]
name = "drue"
version = "0.1.0"
authors = ["Finnkauski <iwiivi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "*"
clap = "*"
huemanity = "0.1.2"
dotenv = "*"
serde_json = "*"
