[package]
name = "drumosphere"
version = "0.1.0"
authors = ["Finnkauski <iwiivi@gmail.com>"]
edition = "2018"
# description="Control your hue lights as you drum some sick beats!"
# license="AGPL-3.0-or-later"
# homepage="https://github.com/finnkauski/drue"
# documentation="https://github.com/finnkauski/drue"
# repository="https://github.com/finnkauski/drue"

[dependencies]
midir = "*"
clap = "*"
huemanity = "0.1.2"
dotenv = "*"
serde_json = "*"
